# gcloud config set project [PROJECT_ID]
# gcloud config set compute/zone [COMPUTE_ZONE]
# gcloud container clusters create [CLUSTER_NAME]
# gcloud container clusters get-credentials [CLUSTER_NAME]
# kubectl apply -f helloweb-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: web
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-app
        image: gcr.io/tasks2-182422/hello-app:v1
        ports:
        - containerPort: 8000
