
# gcloud config set project [PROJECT_ID]
# gcloud config set compute/zone [COMPUTE_ZONE]
# gcloud container clusters create [CLUSTER_NAME]
# gcloud container clusters get-credentials [CLUSTER_NAME]
# kubectl apply -f helloweb-ingress-nodeport.yaml
# kubectl get ingress
# wait for 5 mins and use the ADDRESS to access
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloweb
  annotations:
    kubernetes.io/ingress.global-static-ip-name: helloweb-ip
  labels:
    app: hello
spec:
  backend:
    serviceName: helloweb-backend
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: helloweb-backend
  labels:
    app: hello
spec:
  type: NodePort
  selector:
    app: hello
    tier: web
  ports:
  - port: 80
    targetPort: 8000
